/* Preset maze layouts — community entry is generated by scripts/import-gemtd-mazes.ts */
export type MazeLayoutId = 'community' | 'doubleHelix'

export const mazeLayoutMeta: Record<MazeLayoutId, { name: string; summary: string }> = {
  community: {
    name: '社区满铺',
    summary: '来自 gem-td.com（3p，约 3410 路程 · 571 格）',
  },
  doubleHelix: {
    name: '双螺旋布局',
    summary: '双螺旋迷宫（约 2268 路程 · 386 格）',
  },
} as const
